osx_image: xcode9.4
language: objective-c
branches:
  only:
    - master
# cache: cocoapods
podfile: Example/Podfile 
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RSRealmHelper.xcworkspace -scheme RSRealmHelper-Example -sdk iphonesimulator9.4 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
